services:
  frontend:
    container_name: frontend
    image: frontend
    networks:
      - webapp
    ports:
      - "8085:80"
    volumes:
      - ./src:/app/src
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    command: "nginx -g daemon off;"

  backend:
    container_name: backend
    image: backend

    networks:
      - webapp
    expose:
      - 8638
    environment:
      APP_MODULE: "main:app"
      BIND: "0.0.0.0:5005"


networks:
  webapp:
      driver: bridge